//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealWebService.NanChangLis {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="NanChangLis.PUB0001Soap")]
    public interface PUB0001Soap {
        
        // CODEGEN: 命名空间 http://tempuri.org 的元素名称 input1 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DHC.Published.PUB0001.BS.PUB0001.HOSDocumentRetrieval", ReplyAction="*")]
        DealWebService.NanChangLis.HOSDocumentRetrievalResponse HOSDocumentRetrieval(DealWebService.NanChangLis.HOSDocumentRetrievalRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org 的元素名称 input1 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DHC.Published.PUB0001.BS.PUB0001.HOSDocumentSearch", ReplyAction="*")]
        DealWebService.NanChangLis.HOSDocumentSearchResponse HOSDocumentSearch(DealWebService.NanChangLis.HOSDocumentSearchRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org 的元素名称 input1 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DHC.Published.PUB0001.BS.PUB0001.SaveHOSDocumentInfo", ReplyAction="*")]
        DealWebService.NanChangLis.SaveHOSDocumentInfoResponse SaveHOSDocumentInfo(DealWebService.NanChangLis.SaveHOSDocumentInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HOSDocumentRetrievalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HOSDocumentRetrieval", Namespace="http://tempuri.org", Order=0)]
        public DealWebService.NanChangLis.HOSDocumentRetrievalRequestBody Body;
        
        public HOSDocumentRetrievalRequest() {
        }
        
        public HOSDocumentRetrievalRequest(DealWebService.NanChangLis.HOSDocumentRetrievalRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class HOSDocumentRetrievalRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string input2;
        
        public HOSDocumentRetrievalRequestBody() {
        }
        
        public HOSDocumentRetrievalRequestBody(string input1, string input2) {
            this.input1 = input1;
            this.input2 = input2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HOSDocumentRetrievalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HOSDocumentRetrievalResponse", Namespace="http://tempuri.org", Order=0)]
        public DealWebService.NanChangLis.HOSDocumentRetrievalResponseBody Body;
        
        public HOSDocumentRetrievalResponse() {
        }
        
        public HOSDocumentRetrievalResponse(DealWebService.NanChangLis.HOSDocumentRetrievalResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class HOSDocumentRetrievalResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HOSDocumentRetrievalResult;
        
        public HOSDocumentRetrievalResponseBody() {
        }
        
        public HOSDocumentRetrievalResponseBody(string HOSDocumentRetrievalResult) {
            this.HOSDocumentRetrievalResult = HOSDocumentRetrievalResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HOSDocumentSearchRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HOSDocumentSearch", Namespace="http://tempuri.org", Order=0)]
        public DealWebService.NanChangLis.HOSDocumentSearchRequestBody Body;
        
        public HOSDocumentSearchRequest() {
        }
        
        public HOSDocumentSearchRequest(DealWebService.NanChangLis.HOSDocumentSearchRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class HOSDocumentSearchRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string input2;
        
        public HOSDocumentSearchRequestBody() {
        }
        
        public HOSDocumentSearchRequestBody(string input1, string input2) {
            this.input1 = input1;
            this.input2 = input2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HOSDocumentSearchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HOSDocumentSearchResponse", Namespace="http://tempuri.org", Order=0)]
        public DealWebService.NanChangLis.HOSDocumentSearchResponseBody Body;
        
        public HOSDocumentSearchResponse() {
        }
        
        public HOSDocumentSearchResponse(DealWebService.NanChangLis.HOSDocumentSearchResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class HOSDocumentSearchResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HOSDocumentSearchResult;
        
        public HOSDocumentSearchResponseBody() {
        }
        
        public HOSDocumentSearchResponseBody(string HOSDocumentSearchResult) {
            this.HOSDocumentSearchResult = HOSDocumentSearchResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveHOSDocumentInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveHOSDocumentInfo", Namespace="http://tempuri.org", Order=0)]
        public DealWebService.NanChangLis.SaveHOSDocumentInfoRequestBody Body;
        
        public SaveHOSDocumentInfoRequest() {
        }
        
        public SaveHOSDocumentInfoRequest(DealWebService.NanChangLis.SaveHOSDocumentInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class SaveHOSDocumentInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string input2;
        
        public SaveHOSDocumentInfoRequestBody() {
        }
        
        public SaveHOSDocumentInfoRequestBody(string input1, string input2) {
            this.input1 = input1;
            this.input2 = input2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveHOSDocumentInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveHOSDocumentInfoResponse", Namespace="http://tempuri.org", Order=0)]
        public DealWebService.NanChangLis.SaveHOSDocumentInfoResponseBody Body;
        
        public SaveHOSDocumentInfoResponse() {
        }
        
        public SaveHOSDocumentInfoResponse(DealWebService.NanChangLis.SaveHOSDocumentInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class SaveHOSDocumentInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SaveHOSDocumentInfoResult;
        
        public SaveHOSDocumentInfoResponseBody() {
        }
        
        public SaveHOSDocumentInfoResponseBody(string SaveHOSDocumentInfoResult) {
            this.SaveHOSDocumentInfoResult = SaveHOSDocumentInfoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PUB0001SoapChannel : DealWebService.NanChangLis.PUB0001Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PUB0001SoapClient : System.ServiceModel.ClientBase<DealWebService.NanChangLis.PUB0001Soap>, DealWebService.NanChangLis.PUB0001Soap {
        
        public PUB0001SoapClient() {
        }
        
        public PUB0001SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PUB0001SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PUB0001SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PUB0001SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DealWebService.NanChangLis.HOSDocumentRetrievalResponse DealWebService.NanChangLis.PUB0001Soap.HOSDocumentRetrieval(DealWebService.NanChangLis.HOSDocumentRetrievalRequest request) {
            return base.Channel.HOSDocumentRetrieval(request);
        }
        
        public string HOSDocumentRetrieval(string input1, string input2) {
            DealWebService.NanChangLis.HOSDocumentRetrievalRequest inValue = new DealWebService.NanChangLis.HOSDocumentRetrievalRequest();
            inValue.Body = new DealWebService.NanChangLis.HOSDocumentRetrievalRequestBody();
            inValue.Body.input1 = input1;
            inValue.Body.input2 = input2;
            DealWebService.NanChangLis.HOSDocumentRetrievalResponse retVal = ((DealWebService.NanChangLis.PUB0001Soap)(this)).HOSDocumentRetrieval(inValue);
            return retVal.Body.HOSDocumentRetrievalResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DealWebService.NanChangLis.HOSDocumentSearchResponse DealWebService.NanChangLis.PUB0001Soap.HOSDocumentSearch(DealWebService.NanChangLis.HOSDocumentSearchRequest request) {
            return base.Channel.HOSDocumentSearch(request);
        }
        
        public string HOSDocumentSearch(string input1, string input2) {
            DealWebService.NanChangLis.HOSDocumentSearchRequest inValue = new DealWebService.NanChangLis.HOSDocumentSearchRequest();
            inValue.Body = new DealWebService.NanChangLis.HOSDocumentSearchRequestBody();
            inValue.Body.input1 = input1;
            inValue.Body.input2 = input2;
            DealWebService.NanChangLis.HOSDocumentSearchResponse retVal = ((DealWebService.NanChangLis.PUB0001Soap)(this)).HOSDocumentSearch(inValue);
            return retVal.Body.HOSDocumentSearchResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DealWebService.NanChangLis.SaveHOSDocumentInfoResponse DealWebService.NanChangLis.PUB0001Soap.SaveHOSDocumentInfo(DealWebService.NanChangLis.SaveHOSDocumentInfoRequest request) {
            return base.Channel.SaveHOSDocumentInfo(request);
        }
        
        public string SaveHOSDocumentInfo(string input1, string input2) {
            DealWebService.NanChangLis.SaveHOSDocumentInfoRequest inValue = new DealWebService.NanChangLis.SaveHOSDocumentInfoRequest();
            inValue.Body = new DealWebService.NanChangLis.SaveHOSDocumentInfoRequestBody();
            inValue.Body.input1 = input1;
            inValue.Body.input2 = input2;
            DealWebService.NanChangLis.SaveHOSDocumentInfoResponse retVal = ((DealWebService.NanChangLis.PUB0001Soap)(this)).SaveHOSDocumentInfo(inValue);
            return retVal.Body.SaveHOSDocumentInfoResult;
        }
    }
}
