//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealWebService.BYSY_HIS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://bjgoodwill.com", ConfigurationName="BYSY_HIS.JHHDRWS004Soap")]
    public interface JHHDRWS004Soap {
        
        // CODEGEN: 命名空间 http://bjgoodwill.com 的元素名称 JHHDRWS004AResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://bjgoodwill.com/HDR.BS.JHHDRWS004.JHHDRWS004A", ReplyAction="*")]
        DealWebService.BYSY_HIS.JHHDRWS004AResponse JHHDRWS004A(DealWebService.BYSY_HIS.JHHDRWS004ARequest request);
        
        // CODEGEN: 命名空间 http://bjgoodwill.com 的元素名称 pInput 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://bjgoodwill.com/HDR.BS.JHHDRWS004.JHHDRWS004APatList", ReplyAction="*")]
        DealWebService.BYSY_HIS.JHHDRWS004APatListResponse JHHDRWS004APatList(DealWebService.BYSY_HIS.JHHDRWS004APatListRequest request);
        
        // CODEGEN: 命名空间 http://bjgoodwill.com 的元素名称 StartTime 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://bjgoodwill.com/HDR.BS.JHHDRWS004.JHHDRWS004B", ReplyAction="*")]
        DealWebService.BYSY_HIS.JHHDRWS004BResponse JHHDRWS004B(DealWebService.BYSY_HIS.JHHDRWS004BRequest request);
        
        // CODEGEN: 命名空间 http://bjgoodwill.com 的元素名称 pInput 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://bjgoodwill.com/HDR.BS.JHHDRWS004.JHHDRWS004CPatList", ReplyAction="*")]
        DealWebService.BYSY_HIS.JHHDRWS004CPatListResponse JHHDRWS004CPatList(DealWebService.BYSY_HIS.JHHDRWS004CPatListRequest request);
        
        // CODEGEN: 命名空间 http://bjgoodwill.com 的元素名称 pInput 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://bjgoodwill.com/HDR.BS.JHHDRWS004.JHHDRWS004D", ReplyAction="*")]
        DealWebService.BYSY_HIS.JHHDRWS004DResponse JHHDRWS004D(DealWebService.BYSY_HIS.JHHDRWS004DRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JHHDRWS004ARequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JHHDRWS004A", Namespace="http://bjgoodwill.com", Order=0)]
        public DealWebService.BYSY_HIS.JHHDRWS004ARequestBody Body;
        
        public JHHDRWS004ARequest() {
        }
        
        public JHHDRWS004ARequest(DealWebService.BYSY_HIS.JHHDRWS004ARequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class JHHDRWS004ARequestBody {
        
        public JHHDRWS004ARequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JHHDRWS004AResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JHHDRWS004AResponse", Namespace="http://bjgoodwill.com", Order=0)]
        public DealWebService.BYSY_HIS.JHHDRWS004AResponseBody Body;
        
        public JHHDRWS004AResponse() {
        }
        
        public JHHDRWS004AResponse(DealWebService.BYSY_HIS.JHHDRWS004AResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bjgoodwill.com")]
    public partial class JHHDRWS004AResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string JHHDRWS004AResult;
        
        public JHHDRWS004AResponseBody() {
        }
        
        public JHHDRWS004AResponseBody(string JHHDRWS004AResult) {
            this.JHHDRWS004AResult = JHHDRWS004AResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JHHDRWS004APatListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JHHDRWS004APatList", Namespace="http://bjgoodwill.com", Order=0)]
        public DealWebService.BYSY_HIS.JHHDRWS004APatListRequestBody Body;
        
        public JHHDRWS004APatListRequest() {
        }
        
        public JHHDRWS004APatListRequest(DealWebService.BYSY_HIS.JHHDRWS004APatListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bjgoodwill.com")]
    public partial class JHHDRWS004APatListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pInput;
        
        public JHHDRWS004APatListRequestBody() {
        }
        
        public JHHDRWS004APatListRequestBody(string pInput) {
            this.pInput = pInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JHHDRWS004APatListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JHHDRWS004APatListResponse", Namespace="http://bjgoodwill.com", Order=0)]
        public DealWebService.BYSY_HIS.JHHDRWS004APatListResponseBody Body;
        
        public JHHDRWS004APatListResponse() {
        }
        
        public JHHDRWS004APatListResponse(DealWebService.BYSY_HIS.JHHDRWS004APatListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bjgoodwill.com")]
    public partial class JHHDRWS004APatListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string JHHDRWS004APatListResult;
        
        public JHHDRWS004APatListResponseBody() {
        }
        
        public JHHDRWS004APatListResponseBody(string JHHDRWS004APatListResult) {
            this.JHHDRWS004APatListResult = JHHDRWS004APatListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JHHDRWS004BRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JHHDRWS004B", Namespace="http://bjgoodwill.com", Order=0)]
        public DealWebService.BYSY_HIS.JHHDRWS004BRequestBody Body;
        
        public JHHDRWS004BRequest() {
        }
        
        public JHHDRWS004BRequest(DealWebService.BYSY_HIS.JHHDRWS004BRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bjgoodwill.com")]
    public partial class JHHDRWS004BRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StartTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string EndTime;
        
        public JHHDRWS004BRequestBody() {
        }
        
        public JHHDRWS004BRequestBody(string StartTime, string EndTime) {
            this.StartTime = StartTime;
            this.EndTime = EndTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JHHDRWS004BResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JHHDRWS004BResponse", Namespace="http://bjgoodwill.com", Order=0)]
        public DealWebService.BYSY_HIS.JHHDRWS004BResponseBody Body;
        
        public JHHDRWS004BResponse() {
        }
        
        public JHHDRWS004BResponse(DealWebService.BYSY_HIS.JHHDRWS004BResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bjgoodwill.com")]
    public partial class JHHDRWS004BResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string JHHDRWS004BResult;
        
        public JHHDRWS004BResponseBody() {
        }
        
        public JHHDRWS004BResponseBody(string JHHDRWS004BResult) {
            this.JHHDRWS004BResult = JHHDRWS004BResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JHHDRWS004CPatListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JHHDRWS004CPatList", Namespace="http://bjgoodwill.com", Order=0)]
        public DealWebService.BYSY_HIS.JHHDRWS004CPatListRequestBody Body;
        
        public JHHDRWS004CPatListRequest() {
        }
        
        public JHHDRWS004CPatListRequest(DealWebService.BYSY_HIS.JHHDRWS004CPatListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bjgoodwill.com")]
    public partial class JHHDRWS004CPatListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pInput;
        
        public JHHDRWS004CPatListRequestBody() {
        }
        
        public JHHDRWS004CPatListRequestBody(string pInput) {
            this.pInput = pInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JHHDRWS004CPatListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JHHDRWS004CPatListResponse", Namespace="http://bjgoodwill.com", Order=0)]
        public DealWebService.BYSY_HIS.JHHDRWS004CPatListResponseBody Body;
        
        public JHHDRWS004CPatListResponse() {
        }
        
        public JHHDRWS004CPatListResponse(DealWebService.BYSY_HIS.JHHDRWS004CPatListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bjgoodwill.com")]
    public partial class JHHDRWS004CPatListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string JHHDRWS004CPatListResult;
        
        public JHHDRWS004CPatListResponseBody() {
        }
        
        public JHHDRWS004CPatListResponseBody(string JHHDRWS004CPatListResult) {
            this.JHHDRWS004CPatListResult = JHHDRWS004CPatListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JHHDRWS004DRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JHHDRWS004D", Namespace="http://bjgoodwill.com", Order=0)]
        public DealWebService.BYSY_HIS.JHHDRWS004DRequestBody Body;
        
        public JHHDRWS004DRequest() {
        }
        
        public JHHDRWS004DRequest(DealWebService.BYSY_HIS.JHHDRWS004DRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bjgoodwill.com")]
    public partial class JHHDRWS004DRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pInput;
        
        public JHHDRWS004DRequestBody() {
        }
        
        public JHHDRWS004DRequestBody(string pInput) {
            this.pInput = pInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JHHDRWS004DResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JHHDRWS004DResponse", Namespace="http://bjgoodwill.com", Order=0)]
        public DealWebService.BYSY_HIS.JHHDRWS004DResponseBody Body;
        
        public JHHDRWS004DResponse() {
        }
        
        public JHHDRWS004DResponse(DealWebService.BYSY_HIS.JHHDRWS004DResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bjgoodwill.com")]
    public partial class JHHDRWS004DResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string JHHDRWS004DResult;
        
        public JHHDRWS004DResponseBody() {
        }
        
        public JHHDRWS004DResponseBody(string JHHDRWS004DResult) {
            this.JHHDRWS004DResult = JHHDRWS004DResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface JHHDRWS004SoapChannel : DealWebService.BYSY_HIS.JHHDRWS004Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JHHDRWS004SoapClient : System.ServiceModel.ClientBase<DealWebService.BYSY_HIS.JHHDRWS004Soap>, DealWebService.BYSY_HIS.JHHDRWS004Soap {
        
        public JHHDRWS004SoapClient() {
        }
        
        public JHHDRWS004SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JHHDRWS004SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JHHDRWS004SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JHHDRWS004SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DealWebService.BYSY_HIS.JHHDRWS004AResponse DealWebService.BYSY_HIS.JHHDRWS004Soap.JHHDRWS004A(DealWebService.BYSY_HIS.JHHDRWS004ARequest request) {
            return base.Channel.JHHDRWS004A(request);
        }
        
        public string JHHDRWS004A() {
            DealWebService.BYSY_HIS.JHHDRWS004ARequest inValue = new DealWebService.BYSY_HIS.JHHDRWS004ARequest();
            inValue.Body = new DealWebService.BYSY_HIS.JHHDRWS004ARequestBody();
            DealWebService.BYSY_HIS.JHHDRWS004AResponse retVal = ((DealWebService.BYSY_HIS.JHHDRWS004Soap)(this)).JHHDRWS004A(inValue);
            return retVal.Body.JHHDRWS004AResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DealWebService.BYSY_HIS.JHHDRWS004APatListResponse DealWebService.BYSY_HIS.JHHDRWS004Soap.JHHDRWS004APatList(DealWebService.BYSY_HIS.JHHDRWS004APatListRequest request) {
            return base.Channel.JHHDRWS004APatList(request);
        }
        
        public string JHHDRWS004APatList(string pInput) {
            DealWebService.BYSY_HIS.JHHDRWS004APatListRequest inValue = new DealWebService.BYSY_HIS.JHHDRWS004APatListRequest();
            inValue.Body = new DealWebService.BYSY_HIS.JHHDRWS004APatListRequestBody();
            inValue.Body.pInput = pInput;
            DealWebService.BYSY_HIS.JHHDRWS004APatListResponse retVal = ((DealWebService.BYSY_HIS.JHHDRWS004Soap)(this)).JHHDRWS004APatList(inValue);
            return retVal.Body.JHHDRWS004APatListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DealWebService.BYSY_HIS.JHHDRWS004BResponse DealWebService.BYSY_HIS.JHHDRWS004Soap.JHHDRWS004B(DealWebService.BYSY_HIS.JHHDRWS004BRequest request) {
            return base.Channel.JHHDRWS004B(request);
        }
        
        public string JHHDRWS004B(string StartTime, string EndTime) {
            DealWebService.BYSY_HIS.JHHDRWS004BRequest inValue = new DealWebService.BYSY_HIS.JHHDRWS004BRequest();
            inValue.Body = new DealWebService.BYSY_HIS.JHHDRWS004BRequestBody();
            inValue.Body.StartTime = StartTime;
            inValue.Body.EndTime = EndTime;
            DealWebService.BYSY_HIS.JHHDRWS004BResponse retVal = ((DealWebService.BYSY_HIS.JHHDRWS004Soap)(this)).JHHDRWS004B(inValue);
            return retVal.Body.JHHDRWS004BResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DealWebService.BYSY_HIS.JHHDRWS004CPatListResponse DealWebService.BYSY_HIS.JHHDRWS004Soap.JHHDRWS004CPatList(DealWebService.BYSY_HIS.JHHDRWS004CPatListRequest request) {
            return base.Channel.JHHDRWS004CPatList(request);
        }
        
        public string JHHDRWS004CPatList(string pInput) {
            DealWebService.BYSY_HIS.JHHDRWS004CPatListRequest inValue = new DealWebService.BYSY_HIS.JHHDRWS004CPatListRequest();
            inValue.Body = new DealWebService.BYSY_HIS.JHHDRWS004CPatListRequestBody();
            inValue.Body.pInput = pInput;
            DealWebService.BYSY_HIS.JHHDRWS004CPatListResponse retVal = ((DealWebService.BYSY_HIS.JHHDRWS004Soap)(this)).JHHDRWS004CPatList(inValue);
            return retVal.Body.JHHDRWS004CPatListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DealWebService.BYSY_HIS.JHHDRWS004DResponse DealWebService.BYSY_HIS.JHHDRWS004Soap.JHHDRWS004D(DealWebService.BYSY_HIS.JHHDRWS004DRequest request) {
            return base.Channel.JHHDRWS004D(request);
        }
        
        public string JHHDRWS004D(string pInput) {
            DealWebService.BYSY_HIS.JHHDRWS004DRequest inValue = new DealWebService.BYSY_HIS.JHHDRWS004DRequest();
            inValue.Body = new DealWebService.BYSY_HIS.JHHDRWS004DRequestBody();
            inValue.Body.pInput = pInput;
            DealWebService.BYSY_HIS.JHHDRWS004DResponse retVal = ((DealWebService.BYSY_HIS.JHHDRWS004Soap)(this)).JHHDRWS004D(inValue);
            return retVal.Body.JHHDRWS004DResult;
        }
    }
}
