//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealWebService.NanChangHis {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="NanChangHis.PUB0018Soap")]
    public interface PUB0018Soap {
        
        // CODEGEN: 命名空间 http://tempuri.org 的元素名称 input1 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DHC.Published.PUB0018.BS.PUB0018.HIPManagerInfo", ReplyAction="*")]
        DealWebService.NanChangHis.HIPManagerInfoResponse HIPManagerInfo(DealWebService.NanChangHis.HIPManagerInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HIPManagerInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HIPManagerInfo", Namespace="http://tempuri.org", Order=0)]
        public DealWebService.NanChangHis.HIPManagerInfoRequestBody Body;
        
        public HIPManagerInfoRequest() {
        }
        
        public HIPManagerInfoRequest(DealWebService.NanChangHis.HIPManagerInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class HIPManagerInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string input2;
        
        public HIPManagerInfoRequestBody() {
        }
        
        public HIPManagerInfoRequestBody(string input1, string input2) {
            this.input1 = input1;
            this.input2 = input2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HIPManagerInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HIPManagerInfoResponse", Namespace="http://tempuri.org", Order=0)]
        public DealWebService.NanChangHis.HIPManagerInfoResponseBody Body;
        
        public HIPManagerInfoResponse() {
        }
        
        public HIPManagerInfoResponse(DealWebService.NanChangHis.HIPManagerInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class HIPManagerInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HIPManagerInfoResult;
        
        public HIPManagerInfoResponseBody() {
        }
        
        public HIPManagerInfoResponseBody(string HIPManagerInfoResult) {
            this.HIPManagerInfoResult = HIPManagerInfoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PUB0018SoapChannel : DealWebService.NanChangHis.PUB0018Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PUB0018SoapClient : System.ServiceModel.ClientBase<DealWebService.NanChangHis.PUB0018Soap>, DealWebService.NanChangHis.PUB0018Soap {
        
        public PUB0018SoapClient() {
        }
        
        public PUB0018SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PUB0018SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PUB0018SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PUB0018SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DealWebService.NanChangHis.HIPManagerInfoResponse DealWebService.NanChangHis.PUB0018Soap.HIPManagerInfo(DealWebService.NanChangHis.HIPManagerInfoRequest request) {
            return base.Channel.HIPManagerInfo(request);
        }
        
        public string HIPManagerInfo(string input1, string input2) {
            DealWebService.NanChangHis.HIPManagerInfoRequest inValue = new DealWebService.NanChangHis.HIPManagerInfoRequest();
            inValue.Body = new DealWebService.NanChangHis.HIPManagerInfoRequestBody();
            inValue.Body.input1 = input1;
            inValue.Body.input2 = input2;
            DealWebService.NanChangHis.HIPManagerInfoResponse retVal = ((DealWebService.NanChangHis.PUB0018Soap)(this)).HIPManagerInfo(inValue);
            return retVal.Body.HIPManagerInfoResult;
        }
    }
}
