//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealWebService.BYSY_HIS_New {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.edi.hdr.goodwill.com/", ConfigurationName="BYSY_HIS_New.HdrQueryDataWsImpl")]
    public interface HdrQueryDataWsImpl {
        
        // CODEGEN: 消息部分命名空间  以后生成的消息协定与默认值(http://ws.edi.hdr.goodwill.com/)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        DealWebService.BYSY_HIS_New.testWSResponse testWS(DealWebService.BYSY_HIS_New.testWS request);
        
        // CODEGEN: 命名空间  的元素名称 pInput 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        DealWebService.BYSY_HIS_New.queryDataResponse queryData(DealWebService.BYSY_HIS_New.queryData request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="testWS", WrapperNamespace="http://ws.edi.hdr.goodwill.com/", IsWrapped=true)]
    public partial class testWS {
        
        public testWS() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="testWSResponse", WrapperNamespace="http://ws.edi.hdr.goodwill.com/", IsWrapped=true)]
    public partial class testWSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public testWSResponse() {
        }
        
        public testWSResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class queryData {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="queryData", Namespace="http://ws.edi.hdr.goodwill.com/", Order=0)]
        public DealWebService.BYSY_HIS_New.queryDataBody Body;
        
        public queryData() {
        }
        
        public queryData(DealWebService.BYSY_HIS_New.queryDataBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class queryDataBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pInput;
        
        public queryDataBody() {
        }
        
        public queryDataBody(string pInput) {
            this.pInput = pInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class queryDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="queryDataResponse", Namespace="http://ws.edi.hdr.goodwill.com/", Order=0)]
        public DealWebService.BYSY_HIS_New.queryDataResponseBody Body;
        
        public queryDataResponse() {
        }
        
        public queryDataResponse(DealWebService.BYSY_HIS_New.queryDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class queryDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public queryDataResponseBody() {
        }
        
        public queryDataResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HdrQueryDataWsImplChannel : DealWebService.BYSY_HIS_New.HdrQueryDataWsImpl, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HdrQueryDataWsImplClient : System.ServiceModel.ClientBase<DealWebService.BYSY_HIS_New.HdrQueryDataWsImpl>, DealWebService.BYSY_HIS_New.HdrQueryDataWsImpl {
        
        public HdrQueryDataWsImplClient() {
        }
        
        public HdrQueryDataWsImplClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HdrQueryDataWsImplClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HdrQueryDataWsImplClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HdrQueryDataWsImplClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DealWebService.BYSY_HIS_New.testWSResponse DealWebService.BYSY_HIS_New.HdrQueryDataWsImpl.testWS(DealWebService.BYSY_HIS_New.testWS request) {
            return base.Channel.testWS(request);
        }
        
        public int testWS() {
            DealWebService.BYSY_HIS_New.testWS inValue = new DealWebService.BYSY_HIS_New.testWS();
            DealWebService.BYSY_HIS_New.testWSResponse retVal = ((DealWebService.BYSY_HIS_New.HdrQueryDataWsImpl)(this)).testWS(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DealWebService.BYSY_HIS_New.queryDataResponse DealWebService.BYSY_HIS_New.HdrQueryDataWsImpl.queryData(DealWebService.BYSY_HIS_New.queryData request) {
            return base.Channel.queryData(request);
        }
        
        public string queryData(string pInput) {
            DealWebService.BYSY_HIS_New.queryData inValue = new DealWebService.BYSY_HIS_New.queryData();
            inValue.Body = new DealWebService.BYSY_HIS_New.queryDataBody();
            inValue.Body.pInput = pInput;
            DealWebService.BYSY_HIS_New.queryDataResponse retVal = ((DealWebService.BYSY_HIS_New.HdrQueryDataWsImpl)(this)).queryData(inValue);
            return retVal.Body.@return;
        }
    }
}
