//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealWebService.HBHD_CA {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HBHD_CA.DocumentTransferSoap")]
    public interface DocumentTransferSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 sDocXml 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadDoc", ReplyAction="*")]
        DealWebService.HBHD_CA.UploadDocResponse UploadDoc(DealWebService.HBHD_CA.UploadDocRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 sDocXml 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveDoc", ReplyAction="*")]
        DealWebService.HBHD_CA.RemoveDocResponse RemoveDoc(DealWebService.HBHD_CA.RemoveDocRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadDocRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadDoc", Namespace="http://tempuri.org/", Order=0)]
        public DealWebService.HBHD_CA.UploadDocRequestBody Body;
        
        public UploadDocRequest() {
        }
        
        public UploadDocRequest(DealWebService.HBHD_CA.UploadDocRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadDocRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sDocXml;
        
        public UploadDocRequestBody() {
        }
        
        public UploadDocRequestBody(string sDocXml) {
            this.sDocXml = sDocXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadDocResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadDocResponse", Namespace="http://tempuri.org/", Order=0)]
        public DealWebService.HBHD_CA.UploadDocResponseBody Body;
        
        public UploadDocResponse() {
        }
        
        public UploadDocResponse(DealWebService.HBHD_CA.UploadDocResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadDocResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UploadDocResult;
        
        public UploadDocResponseBody() {
        }
        
        public UploadDocResponseBody(string UploadDocResult) {
            this.UploadDocResult = UploadDocResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveDocRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveDoc", Namespace="http://tempuri.org/", Order=0)]
        public DealWebService.HBHD_CA.RemoveDocRequestBody Body;
        
        public RemoveDocRequest() {
        }
        
        public RemoveDocRequest(DealWebService.HBHD_CA.RemoveDocRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RemoveDocRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sDocXml;
        
        public RemoveDocRequestBody() {
        }
        
        public RemoveDocRequestBody(string sDocXml) {
            this.sDocXml = sDocXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveDocResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveDocResponse", Namespace="http://tempuri.org/", Order=0)]
        public DealWebService.HBHD_CA.RemoveDocResponseBody Body;
        
        public RemoveDocResponse() {
        }
        
        public RemoveDocResponse(DealWebService.HBHD_CA.RemoveDocResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RemoveDocResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RemoveDocResult;
        
        public RemoveDocResponseBody() {
        }
        
        public RemoveDocResponseBody(string RemoveDocResult) {
            this.RemoveDocResult = RemoveDocResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DocumentTransferSoapChannel : DealWebService.HBHD_CA.DocumentTransferSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DocumentTransferSoapClient : System.ServiceModel.ClientBase<DealWebService.HBHD_CA.DocumentTransferSoap>, DealWebService.HBHD_CA.DocumentTransferSoap {
        
        public DocumentTransferSoapClient() {
        }
        
        public DocumentTransferSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DocumentTransferSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentTransferSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentTransferSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DealWebService.HBHD_CA.UploadDocResponse DealWebService.HBHD_CA.DocumentTransferSoap.UploadDoc(DealWebService.HBHD_CA.UploadDocRequest request) {
            return base.Channel.UploadDoc(request);
        }
        
        public string UploadDoc(string sDocXml) {
            DealWebService.HBHD_CA.UploadDocRequest inValue = new DealWebService.HBHD_CA.UploadDocRequest();
            inValue.Body = new DealWebService.HBHD_CA.UploadDocRequestBody();
            inValue.Body.sDocXml = sDocXml;
            DealWebService.HBHD_CA.UploadDocResponse retVal = ((DealWebService.HBHD_CA.DocumentTransferSoap)(this)).UploadDoc(inValue);
            return retVal.Body.UploadDocResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DealWebService.HBHD_CA.RemoveDocResponse DealWebService.HBHD_CA.DocumentTransferSoap.RemoveDoc(DealWebService.HBHD_CA.RemoveDocRequest request) {
            return base.Channel.RemoveDoc(request);
        }
        
        public string RemoveDoc(string sDocXml) {
            DealWebService.HBHD_CA.RemoveDocRequest inValue = new DealWebService.HBHD_CA.RemoveDocRequest();
            inValue.Body = new DealWebService.HBHD_CA.RemoveDocRequestBody();
            inValue.Body.sDocXml = sDocXml;
            DealWebService.HBHD_CA.RemoveDocResponse retVal = ((DealWebService.HBHD_CA.DocumentTransferSoap)(this)).RemoveDoc(inValue);
            return retVal.Body.RemoveDocResult;
        }
    }
}
